alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: pierreb-v-siteservice
    match:
      path:
        prefix: /
name: site-service
region: lon
services:
- http_port: 8080
  image:
    registry: pierreb-v
    registry_credentials: EV[1:BN7cEUz+PICOKLXcvIpmOhKBDy14zQdm:tJNkJ0OLb2eu8HCNNsqOYwi50MpFunlbnGkW30swo/Fe+WgPrG9D3znLnzgyfHOu7YcdlQ3dwKoR052ddcfly8sI]
    registry_type: GHCR
    repository: siteservice
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: pierreb-v-siteservice
